apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-cluster
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: |
    This project is used to deploy applications to the cluster apps cluster.

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/dsmello'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
  - namespace: "*"
    name: apps-cluster

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'


  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true



