apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vitoriametrics-cluster
spec:
  # Add fields here
  retentionPeriod: "1"
  vmstorage:
    replicaCount: 2
  vmselect:
    replicaCount: 2
  vminsert:
    replicaCount: 2